language: ruby
rvm:
  - 2.2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler

#------------------------------
# Update the node version - see http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
env:
  - TRAVIS_NODE_VERSION="5"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

#------------------------------
# Setup
before_script:
  - node -v
  - which bash
  - bash -l rvm env --path --ruby-version
  # update npm
  - npm install npm -g

  # install Gulp 4 CLI tools globally from 4.0 GitHub branch
  #   (had problems with public key denied on branch so had to use https tarball)
  #- npm install gulpjs/gulp-cli#4.0 -g
  #- npm install git://github.com/gulpjs/gulp-cli#4.0 -g
  - npm install https://github.com/gulpjs/gulp-cli/tarball/4.0 -g

#------------------------------
# Build
script: bundle exec rake