language: ruby
rvm:
  - 2.2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler

before_script:
  # install Gulp 4 CLI tools globally from 4.0 GitHub branch
  - npm install gulpjs/gulp-cli#4.0 -g

script: rake