language: ruby
rvm:
  - 2.2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler

before_script:
  - node -v
  - which bash
  - bash -l rvm env --path --ruby-version
  # update npm
  - npm install npm -g

  # install Gulp 4 CLI tools globally from 4.0 GitHub branch
  #   (had problems with public key denied on branch so had to use https tarball)
  #- npm install gulpjs/gulp-cli#4.0 -g
  #- npm install git://github.com/gulpjs/gulp-cli#4.0 -g
  - npm install https://github.com/gulpjs/gulp-cli/tarball/4.0 -g
  - bundle exec rake gulp:tasks

script: bundle exec rake