source 'https://rubygems.org'

gem 'gulp-pipeline-rails', path: '../../'

# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec'
  gem 'rspec-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

